---
title: "Final Project"
author: 'Nicholas Wong'
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  pdf_document: default
---

R set-up 

```{r message = F}
library(tidyverse)
library(ISLR)
library(leaps)
library(glmnet)
library(pls)
library(MASS)
library(caret)
library(corrplot)
library(ggplot2)
library(sf)
library(RColorBrewer)
library(gridExtra)

airbnb <- read_csv("airbnb.csv",
                   col_select = -c("id", "amenities", "description", "name", "thumbnail_url"))
```

**Data pre-processing** 
```{r message = F, include = F}


set.seed(123)

# 80/20 train/test split 
training_indices <- sample(1:74111, 60000)

# Split data into train and test sets 
train <- airbnb[training_indices, ]
test <- airbnb[-training_indices, ] # keep as unseen data 
```

# Method 1 - Forward Selection # 

Forward selection 
```{r}
full = lm(log_price ~., data=train)
none = lm(log_price ~., data = train)
MSE = (summary(full)$sigma)^2
forward_selection_mod <- step(none, scope = list(upper = full), scale = MSE, direction = 'forward', trace=FALSE)

summary(forward_selection_mod)
plot(forward_selection_mod)
```




